In [1]:
import numpy as np

In [2]:
a= [0,1,2,3,4]
b= [5,6,7,8,9]

Problem 1

Write code in the below block toconcatenate the 2 arrays a and b and print the concatenated array. Desired output shown below

In [3]:
np.concatenate((a,b))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Problem 2

Write code in the below block to create a 3rd array, which contains an element wise sum of a and b. Set this new array to a variable called c.

Hint: Use the np.array() function to convert data into more manageable vectors

Desired output shown below

In [4]:
c=np.add(a,b)
print(c)

[ 5  7  9 11 13]


Problem 3

Add unity to each of the elements of array c.

Hint: use np.ones()

The desired output is shown below.

In [25]:
d=np.ones(5, dtype=int)
print(d)

[1 1 1 1 1]


In [24]:
c=np.add(c,d)
print(c)

[ 8 10 12 14 16]
